travis:
  secure:
    BINSTAR_TOKEN: cmvP/srpazRPukZUyFfE/zSi7gAvqPHKJByL6RhOSBTHwZU4to3doNCCZZyqgLyZmFWncD5xgWGBvxcyBcUAZM4Vv80HTrBhwyPvHhYdCpqnU1fop9m5ljQC696aNfn4Hi6R17k+epP4zHrhCi5Etu7BW5z/jYS8zJBWo81PHL+ZoaGCm5r6MzqDKO3D6wwXY6wXXBr9Z9cHt/MpgWH7Q0bwpi6Hzjg7+MMmnHGl1kmhp/XrCXq8LaCpoL8Gc5qI6pkQtrMl0iyA8kU6uOZJPXWpo5MUK8I9w7uHXL11YgN+w/bOk9kMP+y5ZNQ8QnIvtEcW0nw0zB7HMiEZOXIHaLyYcW+UahE2Vgw56ddPbN/WS1vZtEceLGbT7tPT+/uGYWuQPfrOS1m/iMSdKKT9ko+AieSV2sbB+z4CNXo/D0dmCHB6AmXo79b3w/WWjZGCtLs5Zj3TdnxWpukDrifRcDfDFqZCK7ldp1s5B/KA6FarU09MN1Z4SwRA7JXYSLGmP/Vpa/xaXAF7K3gCPHoBVkMop/TpHkj2gef0D3ypUc7cEFUB6Ae7HHqeOz7mwC/ANKWolnBC/FbN4B+AcFPBHkJxe84cY6ECnrUMlCF9s/bkme8oy+0c6yz2GTeRZNbwz797vEvcFQBoGmEp6zotsfXf1DYn+YyHAxaueEu/aoo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
